version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "revision: ${pipeline.git.base_revision} curr: ${pipeline.git.revision}""
            - run: npm install
            - run: npm test
            - run: npm affected:deploy
workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy
