version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node --version
            - run: npm install
            - run: yarn affected:build --base=<< pipeline.git.base_revision >> --head=HEAD
            - run: yarn affected:deploy --base=<< pipeline.git.base_revision >> --head=HEAD --netlifyToken=${NETLIFY_TOKEN}
            - store_artifacts:
              path: /tmp/proj_artifacts

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy
